/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ZBox {
        "align"?: 'center' | 'flex-start' | 'flex-end';
        "as"?: 'header' | 'footer' | 'main' | 'nav' | 'article' | 'section' | 'search' | 'aside';
        "background"?: string;
        "block"?: boolean;
        "border"?: string;
        "borderColor"?: string;
        "borderRadius"?: string;
        "borderStyle"?: string;
        "borderWidth"?: string;
        "boxShadow"?: string;
        "columnGap"?: string;
        "cursor"?: string;
        "flex"?: string;
        "gap"?: string;
        "h"?: string;
        "justify"?: 'center' | 'flex-start' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "m"?: string;
        "mb"?: string;
        "ml"?: string;
        "mr"?: string;
        "mt"?: string;
        "name"?: string;
        "p"?: string;
        "pb"?: string;
        "pl"?: string;
        "pointerEvents"?: string;
        "pr"?: string;
        "pt"?: string;
        "row"?: boolean;
        "rowGap"?: string;
        "w"?: string;
        "wrap"?: boolean;
        "zIndex"?: string;
    }
    interface ZListItemBox {
        "align"?: 'center' | 'flex-start' | 'flex-end';
        "background"?: string;
        "block"?: boolean;
        "border"?: string;
        "borderColor"?: string;
        "borderRadius"?: string;
        "borderStyle"?: string;
        "borderWidth"?: string;
        "boxShadow"?: string;
        "columnGap"?: string;
        "cursor"?: string;
        "flex"?: string;
        "gap"?: string;
        "h"?: string;
        "justify"?: 'center' | 'flex-start' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "m"?: string;
        "mb"?: string;
        "ml"?: string;
        "mr"?: string;
        "mt"?: string;
        "name"?: string;
        "p"?: string;
        "pb"?: string;
        "pl"?: string;
        "pointerEvents"?: string;
        "pr"?: string;
        "pt"?: string;
        "row"?: boolean;
        "rowGap"?: string;
        "w"?: string;
        "wrap"?: boolean;
        "zIndex"?: string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLZBoxElement extends Components.ZBox, HTMLStencilElement {
    }
    var HTMLZBoxElement: {
        prototype: HTMLZBoxElement;
        new (): HTMLZBoxElement;
    };
    interface HTMLZListItemBoxElement extends Components.ZListItemBox, HTMLStencilElement {
    }
    var HTMLZListItemBoxElement: {
        prototype: HTMLZListItemBoxElement;
        new (): HTMLZListItemBoxElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "z-box": HTMLZBoxElement;
        "z-list-item-box": HTMLZListItemBoxElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ZBox {
        "align"?: 'center' | 'flex-start' | 'flex-end';
        "as"?: 'header' | 'footer' | 'main' | 'nav' | 'article' | 'section' | 'search' | 'aside';
        "background"?: string;
        "block"?: boolean;
        "border"?: string;
        "borderColor"?: string;
        "borderRadius"?: string;
        "borderStyle"?: string;
        "borderWidth"?: string;
        "boxShadow"?: string;
        "columnGap"?: string;
        "cursor"?: string;
        "flex"?: string;
        "gap"?: string;
        "h"?: string;
        "justify"?: 'center' | 'flex-start' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "m"?: string;
        "mb"?: string;
        "ml"?: string;
        "mr"?: string;
        "mt"?: string;
        "name"?: string;
        "p"?: string;
        "pb"?: string;
        "pl"?: string;
        "pointerEvents"?: string;
        "pr"?: string;
        "pt"?: string;
        "row"?: boolean;
        "rowGap"?: string;
        "w"?: string;
        "wrap"?: boolean;
        "zIndex"?: string;
    }
    interface ZListItemBox {
        "align"?: 'center' | 'flex-start' | 'flex-end';
        "background"?: string;
        "block"?: boolean;
        "border"?: string;
        "borderColor"?: string;
        "borderRadius"?: string;
        "borderStyle"?: string;
        "borderWidth"?: string;
        "boxShadow"?: string;
        "columnGap"?: string;
        "cursor"?: string;
        "flex"?: string;
        "gap"?: string;
        "h"?: string;
        "justify"?: 'center' | 'flex-start' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "m"?: string;
        "mb"?: string;
        "ml"?: string;
        "mr"?: string;
        "mt"?: string;
        "name"?: string;
        "p"?: string;
        "pb"?: string;
        "pl"?: string;
        "pointerEvents"?: string;
        "pr"?: string;
        "pt"?: string;
        "row"?: boolean;
        "rowGap"?: string;
        "w"?: string;
        "wrap"?: boolean;
        "zIndex"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "z-box": ZBox;
        "z-list-item-box": ZListItemBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "z-box": LocalJSX.ZBox & JSXBase.HTMLAttributes<HTMLZBoxElement>;
            "z-list-item-box": LocalJSX.ZListItemBox & JSXBase.HTMLAttributes<HTMLZListItemBoxElement>;
        }
    }
}
